Add pip check to all the py3- packages.

diff --git a/py3-asttokens.yaml b/py3-asttokens.yaml
--- a/py3-asttokens.yaml
+++ b/py3-asttokens.yaml
@@ -1,17 +1,3 @@
-# Generated from https://pypi.org/project/asttokens/
-package:
-  name: py3-asttokens
-  version: 2.4.1
-  epoch: 1
-  description: Annotate AST trees with source code positions
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - py3-six
-      - py3-typing
-      - python-3
-
 environment:
   contents:
     packages:
@@ -21,6 +7,19 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - py3-six
+      - py3-typing
+      - python-3
+  description: Annotate AST trees with source code positions
+  epoch: 1
+  name: py3-asttokens
+  version: 2.4.1
 
 pipeline:
   - uses: git-checkout
@@ -34,25 +33,15 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"asttokens\"\nIMPORT_STATEMENT=\"import asttokens\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
-  manual: false
   github:
     identifier: gristlabs/asttokens
     strip-prefix: v
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="asttokens"
-        IMPORT_STATEMENT="import asttokens"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+  manual: false
diff --git a/py3-babel.yaml b/py3-babel.yaml
--- a/py3-babel.yaml
+++ b/py3-babel.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-babel
-  version: 2.14.0
-  epoch: 1
-  description: Python3 i18n tool
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -19,11 +8,22 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - python3
+  description: Python3 i18n tool
+  epoch: 1
+  name: py3-babel
+  version: 2.14.0
+
 pipeline:
   - uses: fetch
     with:
-      uri: https://files.pythonhosted.org/packages/source/B/Babel/Babel-${{package.version}}.tar.gz
       expected-sha512: cfcd93bc5e57e3d23b8fb67f77fdeeb08183cc5ef9a6e044085a090cec3d722cf658e740c639f5a834df11a4cff0dacafdbba435184d77a78d56fc0bb6b62fd2
+      uri: https://files.pythonhosted.org/packages/source/B/Babel/Babel-${{package.version}}.tar.gz
 
   - name: Python Build
     runs: python setup.py build
@@ -33,23 +33,13 @@ pipeline:
 
   - uses: strip
 
-update:
-  enabled: true
-  shared: true
-  release-monitor:
-    identifier: 11984
-
 test:
   pipeline:
-    - runs: |
-        LIBRARY="babel"
-        IMPORT_STATEMENT="import babel"
+    - runs: "LIBRARY=\"babel\"\nIMPORT_STATEMENT=\"import babel\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+update:
+  enabled: true
+  release-monitor:
+    identifier: 11984
+  shared: true
diff --git a/py3-backcall.yaml b/py3-backcall.yaml
--- a/py3-backcall.yaml
+++ b/py3-backcall.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/backcall/
-package:
-  name: py3-backcall
-  version: 0.2.0
-  epoch: 2
-  description: Specifications for callback functions passed in to an API
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -19,6 +7,17 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - python-3
+  description: Specifications for callback functions passed in to an API
+  epoch: 2
+  name: py3-backcall
+  version: 0.2.0
 
 pipeline:
   - uses: git-checkout
@@ -32,23 +31,13 @@ pipeline:
 
   - uses: strip
 
-update:
-  enabled: true
-  manual: false
-  github:
-    identifier: takluyver/backcall
-
 test:
   pipeline:
-    - runs: |
-        LIBRARY="backcall"
-        IMPORT_STATEMENT="import backcall"
+    - runs: "LIBRARY=\"backcall\"\nIMPORT_STATEMENT=\"import backcall\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+update:
+  enabled: true
+  github:
+    identifier: takluyver/backcall
+  manual: false
diff --git a/py3-beautifulsoup4.yaml b/py3-beautifulsoup4.yaml
--- a/py3-beautifulsoup4.yaml
+++ b/py3-beautifulsoup4.yaml
@@ -1,16 +1,3 @@
-# Generated from https://pypi.org/project/beautifulsoup4/
-package:
-  name: py3-beautifulsoup4
-  version: 4.12.3
-  epoch: 0
-  description: Screen-scraping library
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - py3-soupsieve
-      - python-3
-
 environment:
   contents:
     packages:
@@ -21,8 +8,19 @@ environment:
       - python-3
       - wolfi-base
   environment:
-    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
     SOURCE_DATE_EPOCH: 315532800
+
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - py3-soupsieve
+      - python-3
+  description: Screen-scraping library
+  epoch: 0
+  name: py3-beautifulsoup4
+  version: 4.12.3
 
 pipeline:
   - uses: fetch
@@ -35,24 +33,14 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"beautifulsoup4\"\nIMPORT_STATEMENT=\"from bs4 import BeautifulSoup\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   ignore-regex-patterns:
-    - 'b\d+'
+    - b\d+
   release-monitor:
     identifier: 3779
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="beautifulsoup4"
-        IMPORT_STATEMENT="from bs4 import BeautifulSoup"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-bleach.yaml b/py3-bleach.yaml
--- a/py3-bleach.yaml
+++ b/py3-bleach.yaml
@@ -1,17 +1,3 @@
-# Generated from https://pypi.org/project/bleach/
-package:
-  name: py3-bleach
-  version: 6.1.0
-  epoch: 2
-  description: An easy safelist-based HTML-sanitizing tool.
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - py3-six
-      - py3-webencodings
-      - python-3
-
 environment:
   contents:
     packages:
@@ -21,6 +7,19 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - py3-six
+      - py3-webencodings
+      - python-3
+  description: An easy safelist-based HTML-sanitizing tool.
+  epoch: 2
+  name: py3-bleach
+  version: 6.1.0
 
 pipeline:
   - uses: git-checkout
@@ -34,25 +33,15 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"bleach\"\nIMPORT_STATEMENT=\"import bleach\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
-  manual: false
   github:
     identifier: mozilla/bleach
     strip-prefix: v
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="bleach"
-        IMPORT_STATEMENT="import bleach"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+  manual: false
diff --git a/py3-blinker.yaml b/py3-blinker.yaml
--- a/py3-blinker.yaml
+++ b/py3-blinker.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-blinker
-  version: 1.8.2
-  epoch: 0
-  description: Fast, simple object-to-object and broadcast signaling
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -23,37 +12,40 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python3
+  description: Fast, simple object-to-object and broadcast signaling
+  epoch: 0
+  name: py3-blinker
+  version: 1.8.2
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 0a6be69aaaf72917bbedf41643f83128c8623075
       repository: https://github.com/pallets-eco/blinker/
       tag: ${{package.version}}
-      expected-commit: 0a6be69aaaf72917bbedf41643f83128c8623075
 
-  - runs: |
-      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 3 3>&1 >&2
+  - runs: 'python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 3 3>&1 >&2
 
-  - runs: |
-      python3 -m installer -d "${{targets.destdir}}" dist/blinker*.whl
+    '
+
+  - runs: 'python3 -m installer -d "${{targets.destdir}}" dist/blinker*.whl
+
+    '
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"blinker\"\nIMPORT_STATEMENT=\"from blinker import Signal\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: pallets-eco/blinker
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="blinker"
-        IMPORT_STATEMENT="from blinker import Signal"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-bokeh.yaml b/py3-bokeh.yaml
--- a/py3-bokeh.yaml
+++ b/py3-bokeh.yaml
@@ -1,24 +1,3 @@
-# Generated from https://pypi.org/project/bokeh/
-package:
-  name: py3-bokeh
-  version: 3.5.1
-  epoch: 0
-  description: Interactive plots and applications in the browser from Python
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - py3-jinja2
-      - py3-contourpy
-      - numpy
-      - py3-packaging
-      - py3-pandas
-      - py3-pillow
-      - py3-pyyaml
-      - py3-tornado
-      - py3-xyzservices
-      - python-3
-
 environment:
   contents:
     packages:
@@ -28,6 +7,26 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - numpy
+      - py3-contourpy
+      - py3-jinja2
+      - py3-packaging
+      - py3-pandas
+      - py3-pillow
+      - py3-pyyaml
+      - py3-tornado
+      - py3-xyzservices
+      - python-3
+  description: Interactive plots and applications in the browser from Python
+  epoch: 0
+  name: py3-bokeh
+  version: 3.5.1
 
 pipeline:
   - uses: fetch
@@ -40,22 +39,12 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"bokeh\"\nIMPORT_STATEMENT=\"import bokeh\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   release-monitor:
     identifier: 78655
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="bokeh"
-        IMPORT_STATEMENT="import bokeh"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-boltons.yaml b/py3-boltons.yaml
--- a/py3-boltons.yaml
+++ b/py3-boltons.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-boltons
-  version: 24.0.0
-  epoch: 0
-  description: When they're not builtins, they're boltons.
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -20,41 +9,34 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - python3
+  description: When they're not builtins, they're boltons.
+  epoch: 0
+  name: py3-boltons
+  version: 24.0.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 992a58c1036fcf4d52cbf3313b6217b7c07b11d9
       repository: https://github.com/mahmoud/boltons
       tag: ${{package.version}}
-      expected-commit: 992a58c1036fcf4d52cbf3313b6217b7c07b11d9
 
-  - runs: |
-      python3 -m gpep517 build-wheel \
-        --wheel-dir dist \
-        --output-fd 3 3>&1 >&2
-      python3 -m installer \
-        -d "${{targets.destdir}}" \
-        dist/boltons-${{package.version}}-*.whl
-      install -Dm644 LICENSE \
-        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE
+  - runs: "python3 -m gpep517 build-wheel \\\n  --wheel-dir dist \\\n  --output-fd 3 3>&1 >&2\npython3 -m installer \\\n  -d \"${{targets.destdir}}\" \\\n  dist/boltons-${{package.version}}-*.whl\ninstall -Dm644 LICENSE \\\n  \"${{targets.destdir}}\"/usr/share/licenses/${{package.name}}/LICENSE\n"
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"boltons\"\nIMPORT_STATEMENT=\"import boltons\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: mahmoud/boltons
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="boltons"
-        IMPORT_STATEMENT="import boltons"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-botocore.yaml b/py3-botocore.yaml
--- a/py3-botocore.yaml
+++ b/py3-botocore.yaml
@@ -1,17 +1,3 @@
-package:
-  name: py3-botocore
-  version: 1.35.0
-  epoch: 0
-  description: The low-level, core functionality of Boto3
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - py3-dateutil
-      - py3-docutils
-      - py3-jmespath
-      - py3-urllib3
-
 environment:
   contents:
     packages:
@@ -22,39 +8,44 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - py3-dateutil
+      - py3-docutils
+      - py3-jmespath
+      - py3-urllib3
+  description: The low-level, core functionality of Boto3
+  epoch: 0
+  name: py3-botocore
+  version: 1.35.0
+
 pipeline:
   - uses: fetch
     with:
-      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
       expected-sha256: 6ab2f5a5cbdaa639599e3478c65462c6d6a10173dc8b941bfc69b0c9eb548f45
+      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
 
-  - runs: |
-      python3 setup.py build
+  - runs: 'python3 setup.py build
 
-  - runs: |
-      python3 setup.py install --prefix=/usr --root="${{targets.contextdir}}" --skip-build
+    '
 
-  # Fix permissions; this has 777 permissions by default.
+  - runs: 'python3 setup.py install --prefix=/usr --root="${{targets.contextdir}}" --skip-build
+
+    '
+
   - runs: chmod -R 755 ${{targets.contextdir}}/usr/lib/python3.12/site-packages/botocore/data/ec2/2016-11-15/waiters-2.json
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"botocore\"\nIMPORT_STATEMENT=\"import botocore\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   release-monitor:
     identifier: 29738
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="botocore"
-        IMPORT_STATEMENT="import botocore"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-bracex.yaml b/py3-bracex.yaml
--- a/py3-bracex.yaml
+++ b/py3-bracex.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-bracex
-  version: "2.5"
-  epoch: 0
-  description: Bash style brace expander.
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,45 +10,35 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python3
+  description: Bash style brace expander.
+  epoch: 0
+  name: py3-bracex
+  version: '2.5'
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 565f7a873b1a87e6890cdcbdbdfa834b775e495b
       repository: https://github.com/facelessuser/bracex
       tag: ${{package.version}}
-      expected-commit: 565f7a873b1a87e6890cdcbdbdfa834b775e495b
 
-  - runs: |
-      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
-      export SOURCE_DATE_EPOCH=315532800
-      python3 -m pip install -U hatchling
-      python3 -m gpep517 build-wheel \
-        --wheel-dir dist \
-        --output-fd 3 3>&1 >&2
-      python3 -m installer \
-        -d "${{targets.destdir}}" \
-        dist/bracex-${{package.version}}-*.whl
-      install -Dm644 LICENSE.md \
-        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE
+  - runs: "# This is needed to work around the error \"ValueError: ZIP does not support timestamps before 1980\"\nexport SOURCE_DATE_EPOCH=315532800\npython3 -m pip install -U hatchling\npython3 -m gpep517 build-wheel \\\n  --wheel-dir dist \\\n  --output-fd 3 3>&1 >&2\npython3 -m installer \\\n  -d \"${{targets.destdir}}\" \\\n  dist/bracex-${{package.version}}-*.whl\ninstall -Dm644 LICENSE.md \\\n  \"${{targets.destdir}}\"/usr/share/licenses/${{package.name}}/LICENSE\n"
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"bracex\"\nIMPORT_STATEMENT=\"import bracex\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: facelessuser/bracex
     strip-suffix: .post1
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="bracex"
-        IMPORT_STATEMENT="import bracex"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cachecontrol.yaml b/py3-cachecontrol.yaml
--- a/py3-cachecontrol.yaml
+++ b/py3-cachecontrol.yaml
@@ -1,19 +1,3 @@
-# Generated from https://pypi.org/project/CacheControl/
-package:
-  name: py3-cachecontrol
-  version: 0.14.0
-  epoch: 1
-  description: httplib2 caching for requests
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - py3-requests
-      - py3-msgpack
-      - python-3
-    provides:
-      - py3-CacheControl=${{package.full-version}}
-
 environment:
   contents:
     packages:
@@ -24,37 +8,42 @@ environment:
       - python-3
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    provides:
+      - py3-CacheControl=${{package.full-version}}
+    runtime:
+      - py3-msgpack
+      - py3-requests
+      - python-3
+  description: httplib2 caching for requests
+  epoch: 1
+  name: py3-cachecontrol
+  version: 0.14.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: e2be0c2f8e7c61ab5e2611dd58748f803f520d4d
       repository: https://github.com/psf/cachecontrol
       tag: v${{package.version}}
-      expected-commit: e2be0c2f8e7c61ab5e2611dd58748f803f520d4d
 
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cachecontrol\"\nIMPORT_STATEMENT=\"import cachecontrol\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: psf/cachecontrol
-    use-tag: true
-    tag-filter: v
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cachecontrol"
-        IMPORT_STATEMENT="import cachecontrol"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+    tag-filter: v
+    use-tag: true
diff --git a/py3-cachetools.yaml b/py3-cachetools.yaml
--- a/py3-cachetools.yaml
+++ b/py3-cachetools.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-cachetools
-  version: 5.5.0
-  epoch: 0
-  description: Extensible memoizing collections and decorators
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -19,12 +8,23 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python3
+  description: Extensible memoizing collections and decorators
+  epoch: 0
+  name: py3-cachetools
+  version: 5.5.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 6c78a8ff67b21834c3873cc918d87b2c5cb22e5c
       repository: https://github.com/tkem/cachetools/
       tag: v${{package.version}}
-      expected-commit: 6c78a8ff67b21834c3873cc918d87b2c5cb22e5c
 
   - name: Python Build
     runs: python setup.py build
@@ -34,24 +34,14 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cachetools\"\nIMPORT_STATEMENT=\"from cachetools import TTLCache\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: tkem/cachetools
     strip-prefix: v
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cachetools"
-        IMPORT_STATEMENT="from cachetools import TTLCache"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cairo.yaml b/py3-cairo.yaml
--- a/py3-cairo.yaml
+++ b/py3-cairo.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-cairo
-  version: 1.26.1
-  epoch: 0
-  description: Python3 bindings for the cairo graphics library
-  copyright:
-    - license: LGPL-2.0-or-later
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -25,17 +14,29 @@ environment:
       - python3-dev
       - zlib-dev
 
+package:
+  copyright:
+    - license: LGPL-2.0-or-later
+  dependencies:
+    runtime:
+      - python3
+  description: Python3 bindings for the cairo graphics library
+  epoch: 0
+  name: py3-cairo
+  version: 1.26.1
+
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/pygobject/pycairo
       expected-commit: 49c89e21c9f11006d37841f920af060cc7d70999
+      repository: https://github.com/pygobject/pycairo
       tag: v${{package.version}}
 
   - uses: meson/configure
     with:
-      opts: |
-        -Db_lto=true
+      opts: '-Db_lto=true
+
+      '
 
   - uses: meson/compile
 
@@ -46,31 +47,21 @@ pipeline:
   - uses: strip
 
 subpackages:
-  - name: py3-cairo-dev
-    pipeline:
-      - uses: split/dev
-    dependencies:
+  - dependencies:
       runtime:
         - py3-cairo
     description: py3-cairo dev
+    name: py3-cairo-dev
+    pipeline:
+      - uses: split/dev
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cairo\"\nIMPORT_STATEMENT=\"import cairo\"\n\nif ! python3 -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python3 -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: pygobject/pycairo
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cairo"
-        IMPORT_STATEMENT="import cairo"
-
-        if ! python3 -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python3 -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-canonicaljson.yaml b/py3-canonicaljson.yaml
--- a/py3-canonicaljson.yaml
+++ b/py3-canonicaljson.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-canonicaljson
-  version: 2.0.0
-  epoch: 0
-  description: Canonical JSON
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -19,17 +8,33 @@ environment:
       - python-3
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - python-3
+  description: Canonical JSON
+  epoch: 0
+  name: py3-canonicaljson
+  version: 2.0.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: ebe1deeb8d24e44ae5f41156c6139febd807d17f
       repository: https://github.com/matrix-org/python-canonicaljson
       tag: v${{package.version}}
-      expected-commit: ebe1deeb8d24e44ae5f41156c6139febd807d17f
 
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"canonicaljson\"\nIMPORT_STATEMENT=\"import canonicaljson\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
@@ -37,18 +42,3 @@ update:
     identifier: matrix-org/python-canonicaljson
     strip-prefix: v
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="canonicaljson"
-        IMPORT_STATEMENT="import canonicaljson"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cassandra-medusa.yaml b/py3-cassandra-medusa.yaml
--- a/py3-cassandra-medusa.yaml
+++ b/py3-cassandra-medusa.yaml
@@ -1,19 +1,3 @@
-# Generated from https://pypi.org/project/cassandra-medusa/
-package:
-  name: py3-cassandra-medusa
-  version: 0.22.1
-  epoch: 0
-  description: Apache Cassandra backup and restore tool
-  copyright:
-    - license: Apache-2.0
-  options:
-    no-provides: true
-    no-depends: true
-  dependencies:
-    runtime:
-      - poetry
-      - python-3.11-base
-
 environment:
   contents:
     packages:
@@ -26,86 +10,134 @@ environment:
       - python-3.11-dev
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - poetry
+      - python-3.11-base
+  description: Apache Cassandra backup and restore tool
+  epoch: 0
+  name: py3-cassandra-medusa
+  options:
+    no-depends: true
+    no-provides: true
+  version: 0.22.1
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: c5b5c475285458a067a69a1c5aa379786928eb0b
       repository: https://github.com/thelastpickle/cassandra-medusa
       tag: v${{package.version}}
-      expected-commit: c5b5c475285458a067a69a1c5aa379786928eb0b
 
   - name: Python Build
-    runs: |
-      pip install wheel
+    runs: 'pip install wheel
+
       pip install poetry
+
       poetry add "aiohttp==3.9.4"
+
       poetry add "certifi==2024.7.4"
+
       poetry add "dnspython==2.6.1"
+
       poetry add "idna==3.7"
+
       # CVE-2024-35195: requests
+
       poetry add "requests@^2.23.0"
+
       # GHSA-m5vv-6r4h-3vj9: azure-identity
+
       poetry add "azure-identity==1.16.1"
+
       # GHSA-34jh-p97f-mpxf: urllib3
+
       poetry add "urllib3==1.26.19"
+
       poetry run pip freeze | grep -v cassandra-medusa > requirements.txt
+
       POETRY_VIRTUALENVS_IN_PROJECT=true poetry install
+
       poetry build
 
-  - runs: |
-      # Setup the virtualenv
+    '
+
+  - runs: '# Setup the virtualenv
+
       python -m venv .venv --system-site-packages
+
       # Bump pip to patch a CVE
+
       .venv/bin/pip install --upgrade pip==24.0 setuptools==70.0.0
 
-  - runs: |
-      .venv/bin/pip install -I -r requirements.txt --no-compile
+    '
+
+  - runs: '.venv/bin/pip install -I -r requirements.txt --no-compile
+
       .venv/bin/pip install -I --no-compile dist/*.whl
 
-  - runs: |
-      # python-snappy is required to run medusa using $MEDUSA_MODE=GRPC.
+    '
+
+  - runs: '# python-snappy is required to run medusa using $MEDUSA_MODE=GRPC.
+
       .venv/bin/pip install -I python-snappy --no-compile
 
-  - runs: |
-      mkdir -p ${{targets.destdir}}/home/cassandra
+    '
+
+  - runs: 'mkdir -p ${{targets.destdir}}/home/cassandra
+
       mv .venv ${{targets.destdir}}/home/cassandra/
 
+
       # edit the venv paths
+
       sed -i "s|/home/build|${{targets.destdir}}/home/cassandra|g" ${{targets.destdir}}/home/cassandra/.venv/bin/*
 
+
       # allow site-packages
+
       sed -i "s|include-system-site-packages = false|include-system-site-packages = true|g" ${{targets.destdir}}/home/cassandra/.venv/pyvenv.cfg
 
-  - runs: |
-      mkdir -p ${{targets.destdir}}/usr/bin
+    '
+
+  - runs: 'mkdir -p ${{targets.destdir}}/usr/bin
+
       cp k8s/medusa.sh ${{targets.destdir}}/usr/bin/medusa
+
       chmod +x ${{targets.destdir}}/usr/bin/medusa
 
-  - runs: |
-      cp pyproject.toml ${{targets.destdir}}/home/cassandra
+    '
+
+  - runs: 'cp pyproject.toml ${{targets.destdir}}/home/cassandra
+
       cp k8s/docker-entrypoint.sh ${{targets.destdir}}/home/cassandra
+
       chmod +x ${{targets.destdir}}/home/cassandra/docker-entrypoint.sh
 
+    '
+
 subpackages:
-  - name: "${{package.name}}-compat"
-    description: "Compatibility package to place binaries and docker entrypoints in the location expected by upstream helm charts"
-    dependencies:
+  - dependencies:
       runtime:
-        # The entrypoint script fails to start without bash and sleep (which comes from busybox)
         - bash
         - busybox
+    description: Compatibility package to place binaries and docker entrypoints in the location expected by upstream helm charts
+    name: ${{package.name}}-compat
     pipeline:
-      - runs: |
-          mkdir -p "${{targets.subpkgdir}}/home/cassandra/"
+      - runs: 'mkdir -p "${{targets.subpkgdir}}/home/cassandra/"
+
           ln -sf /usr/bin/medusa ${{targets.subpkgdir}}/home/cassandra/medusa
+
           # Symlink the binary from usr/bin to /bin
+
           mkdir -p "${{targets.subpkgdir}}"/bin
+
           ln -sf /usr/bin/grpc-health-probe ${{targets.subpkgdir}}/bin/grpc_health_probe
 
-update:
-  enabled: true
-  github:
-    identifier: thelastpickle/cassandra-medusa
-    strip-prefix: v
+        '
 
 test:
   environment:
@@ -116,10 +148,23 @@ test:
         - grpc-health-probe
   pipeline:
     - runs: medusa --version
-    - runs: |
-        set +e
+    - runs: 'set +e
+
         fail() { echo "$@" 1>&2; exit 1; }
+
         out=$(/home/cassandra/.venv/bin/python3 -m medusa.service.grpc.server 2>&1)
+
         status=$?
-        echo "$out" | grep -q '/etc/medusa/medusa.ini' || fail "medusa.service.grpc.server output did not contain expected 'medusa.ini' message. Exit status $status: $out"
+
+        echo "$out" | grep -q ''/etc/medusa/medusa.ini'' || fail "medusa.service.grpc.server output did not contain expected ''medusa.ini'' message. Exit status $status: $out"
+
         echo "medusa.service.grpc.server exited with expected error message"
+
+      '
+    - uses: py/pip-check
+
+update:
+  enabled: true
+  github:
+    identifier: thelastpickle/cassandra-medusa
+    strip-prefix: v
diff --git a/py3-click.yaml b/py3-click.yaml
--- a/py3-click.yaml
+++ b/py3-click.yaml
@@ -1,17 +1,3 @@
-# Generated from https://pypi.org/project/click/
-package:
-  name: py3-click
-  version: 8.1.7
-  epoch: 3
-  description: Composable command line interface toolkit
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - py3-colorama
-      - py3-importlib-metadata
-      - python3
-
 environment:
   contents:
     packages:
@@ -22,12 +8,25 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - py3-colorama
+      - py3-importlib-metadata
+      - python3
+  description: Composable command line interface toolkit
+  epoch: 3
+  name: py3-click
+  version: 8.1.7
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 874ca2bc1c30d93a4ac6e36a15ed685eafe89097
       repository: https://github.com/pallets/click
       tag: ${{package.version}}
-      expected-commit: 874ca2bc1c30d93a4ac6e36a15ed685eafe89097
 
   - name: Python Build
     runs: python setup.py build
@@ -37,22 +36,12 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"click\"\nIMPORT_STATEMENT=\"import click\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: pallets/click
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="click"
-        IMPORT_STATEMENT="import click"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cmaes.yaml b/py3-cmaes.yaml
--- a/py3-cmaes.yaml
+++ b/py3-cmaes.yaml
@@ -1,16 +1,3 @@
-package:
-  name: py3-cmaes
-  version: 0.10.0
-  epoch: 3
-  description: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - numpy
-      - py3-scipy
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,11 +8,24 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - numpy
+      - py3-scipy
+      - python3
+  description: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
+  epoch: 3
+  name: py3-cmaes
+  version: 0.10.0
+
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/CyberAgentAILab/cmaes
       expected-commit: 4ebcdbd412333893bd2674bc694924e21abf8915
+      repository: https://github.com/CyberAgentAILab/cmaes
       tag: v${{package.version}}
 
   - name: Python Build
@@ -36,23 +36,13 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cmaes\"\nIMPORT_STATEMENT=\"from cmaes import CMA\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: CyberAgentAILab/cmaes
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cmaes"
-        IMPORT_STATEMENT="from cmaes import CMA"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-colorlog.yaml b/py3-colorlog.yaml
--- a/py3-colorlog.yaml
+++ b/py3-colorlog.yaml
@@ -1,15 +1,3 @@
-package:
-  name: py3-colorlog
-  version: 6.8.2
-  epoch: 0
-  description: Add colours to the output of Python's logging module.
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - py3-colorama
-      - python3
-
 environment:
   contents:
     packages:
@@ -20,11 +8,23 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - py3-colorama
+      - python3
+  description: Add colours to the output of Python's logging module.
+  epoch: 0
+  name: py3-colorlog
+  version: 6.8.2
+
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/borntyping/python-colorlog
       expected-commit: 3d95fe86a5145081eb20c5c7acf529d3bbc10857
+      repository: https://github.com/borntyping/python-colorlog
       tag: v${{package.version}}
 
   - name: Python Build
@@ -35,23 +35,13 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"colorlog\"\nIMPORT_STATEMENT=\"import colorlog\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: borntyping/python-colorlog
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="colorlog"
-        IMPORT_STATEMENT="import colorlog"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-configobj.yaml b/py3-configobj.yaml
--- a/py3-configobj.yaml
+++ b/py3-configobj.yaml
@@ -1,16 +1,3 @@
-# Generated from https://pypi.org/project/configobj/
-package:
-  name: py3-configobj
-  version: 5.0.8
-  epoch: 2
-  description: Config file reading, writing and validation.
-  copyright:
-    - license: BSD-2-Clause
-  dependencies:
-    runtime:
-      - py3-six
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,12 +8,24 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-2-Clause
+  dependencies:
+    runtime:
+      - py3-six
+      - python3
+  description: Config file reading, writing and validation.
+  epoch: 2
+  name: py3-configobj
+  version: 5.0.8
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: a58c2f4de0e9e854daa67fec630506e5a461eea9
       repository: https://github.com/DiffSK/configobj
       tag: v${{package.version}}
-      expected-commit: a58c2f4de0e9e854daa67fec630506e5a461eea9
 
   - name: Python Build
     runs: python setup.py build
@@ -36,24 +35,14 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"configobj\"\nIMPORT_STATEMENT=\"from configobj import ConfigObj\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: DiffSK/configobj
     strip-prefix: v
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="configobj"
-        IMPORT_STATEMENT="from configobj import ConfigObj"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-contextlib2.yaml b/py3-contextlib2.yaml
--- a/py3-contextlib2.yaml
+++ b/py3-contextlib2.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-contextlib2
-  version: 21.6.0
-  epoch: 4
-  description: backports of the contextlib module from newer versions of python
-  copyright:
-    - license: PSF-2.0 AND Apache-2.0
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -19,36 +8,39 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: PSF-2.0 AND Apache-2.0
+  dependencies:
+    runtime:
+      - python3
+  description: backports of the contextlib module from newer versions of python
+  epoch: 4
+  name: py3-contextlib2
+  version: 21.6.0
+
 pipeline:
   - uses: fetch
     with:
-      uri: https://files.pythonhosted.org/packages/source/c/contextlib2/contextlib2-${{package.version}}.tar.gz
       expected-sha256: ab1e2bfe1d01d968e1b7e8d9023bc51ef3509bba217bb730cee3827e1ee82869
+      uri: https://files.pythonhosted.org/packages/source/c/contextlib2/contextlib2-${{package.version}}.tar.gz
 
-  - runs: |
-      python3 setup.py build
+  - runs: 'python3 setup.py build
 
-  - runs: |
-      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
+    '
+
+  - runs: 'python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
+
+    '
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"contextlib2\"\nIMPORT_STATEMENT=\"import contextlib2\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   release-monitor:
     identifier: 6215
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="contextlib2"
-        IMPORT_STATEMENT="import contextlib2"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-contourpy.yaml b/py3-contourpy.yaml
--- a/py3-contourpy.yaml
+++ b/py3-contourpy.yaml
@@ -1,15 +1,3 @@
-package:
-  name: py3-contourpy
-  version: 1.2.1
-  epoch: 1
-  description: Python library for calculating contours of 2D quadrilateral grids
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - numpy
-      - python3
-
 environment:
   contents:
     packages:
@@ -25,39 +13,43 @@ environment:
       - python3-dev
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - numpy
+      - python3
+  description: Python library for calculating contours of 2D quadrilateral grids
+  epoch: 1
+  name: py3-contourpy
+  version: 1.2.1
+
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/contourpy/contourpy
       expected-commit: bc805ed85d711873232873af8a47a8effd224fa3
+      repository: https://github.com/contourpy/contourpy
       tag: v${{package.version}}
 
   - name: Python Build
-    runs: |
-      python3 -m build
+    runs: 'python3 -m build
 
-  - runs: |
-      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
+    '
+
+  - runs: 'python3 -m installer -d "${{targets.destdir}}" dist/*.whl
+
+    '
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"contourpy\"\nIMPORT_STATEMENT=\"import contourpy\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: contourpy/contourpy
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="contourpy"
-        IMPORT_STATEMENT="import contourpy"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-crcmod.yaml b/py3-crcmod.yaml
--- a/py3-crcmod.yaml
+++ b/py3-crcmod.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-crcmod
-  version: '1.7'
-  epoch: 3
-  description: Cyclic Redundancy Check (CRC) implementation in Python
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -21,39 +10,43 @@ environment:
       - python-3-dev
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python-3
+  description: Cyclic Redundancy Check (CRC) implementation in Python
+  epoch: 3
+  name: py3-crcmod
+  version: '1.7'
+
 pipeline:
   - uses: fetch
     with:
-      uri: https://files.pythonhosted.org/packages/source/c/crcmod/crcmod-${{package.version}}.tar.gz
       expected-sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e
+      uri: https://files.pythonhosted.org/packages/source/c/crcmod/crcmod-${{package.version}}.tar.gz
 
   - name: Python Build
-    runs: |
-      python3 -m gpep517 build-wheel \
+    runs: 'python3 -m gpep517 build-wheel \
+
       --wheel-dir .dist \
+
       --output-fd 3 3>&1 >&2
+
+    '
 
   - name: Python install
     runs: python3 -m installer --destdir="${{targets.destdir}}" .dist/*.whl
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"crcmod\"\nIMPORT_STATEMENT=\"import crcmod\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   release-monitor:
     identifier: 12017
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="crcmod"
-        IMPORT_STATEMENT="import crcmod"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cryptography.yaml b/py3-cryptography.yaml
--- a/py3-cryptography.yaml
+++ b/py3-cryptography.yaml
@@ -1,16 +1,3 @@
-# Generated from https://pypi.org/project/cryptography/
-package:
-  name: py3-cryptography
-  version: 43.0.0
-  epoch: 0
-  description: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
-  copyright:
-    - license: Apache-2.0 OR BSD-3-Clause
-  dependencies:
-    runtime:
-      - py3-cffi
-      - python3
-
 environment:
   contents:
     packages:
@@ -26,35 +13,37 @@ environment:
       - rust
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0 OR BSD-3-Clause
+  dependencies:
+    runtime:
+      - py3-cffi
+      - python3
+  description: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
+  epoch: 0
+  name: py3-cryptography
+  version: 43.0.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: ebf14f2edc8536f36797979cb0e075e766d978c5
       repository: https://github.com/pyca/cryptography/
       tag: ${{package.version}}
-      expected-commit: ebf14f2edc8536f36797979cb0e075e766d978c5
 
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cryptography\"\nIMPORT_STATEMENT=\"import cryptography\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: pyca/cryptography
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cryptography"
-        IMPORT_STATEMENT="import cryptography"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-cycler.yaml b/py3-cycler.yaml
--- a/py3-cycler.yaml
+++ b/py3-cycler.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-cycler
-  version: 0.12.1
-  epoch: 1
-  description: Composable style cycles
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,39 +10,41 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - python3
+  description: Composable style cycles
+  epoch: 1
+  name: py3-cycler
+  version: 0.12.1
+
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/matplotlib/cycler
       expected-commit: 6115d5c55d66cdedb67ec5a0d6b52b6df52fd9d2
+      repository: https://github.com/matplotlib/cycler
       tag: v${{package.version}}
 
   - name: Python Build
-    runs: |
-      python -m build
+    runs: 'python -m build
+
+    '
 
   - name: Python Install
     runs: python3 -m installer -d "${{targets.destdir}}" dist/*.whl
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"cycler\"\nIMPORT_STATEMENT=\"from cycler import cycler\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: matplotlib/cycler
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="cycler"
-        IMPORT_STATEMENT="from cycler import cycler"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-debugpy.yaml b/py3-debugpy.yaml
--- a/py3-debugpy.yaml
+++ b/py3-debugpy.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/debugpy/
-package:
-  name: py3-debugpy
-  version: 1.8.5
-  epoch: 0
-  description: An implementation of the Debug Adapter Protocol for Python
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -19,6 +7,17 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python-3
+  description: An implementation of the Debug Adapter Protocol for Python
+  epoch: 0
+  name: py3-debugpy
+  version: 1.8.5
 
 pipeline:
   - uses: git-checkout
@@ -32,26 +31,16 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"debugpy\"\nIMPORT_STATEMENT=\"import debugpy\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
-  manual: false
-  ignore-regex-patterns:
-    - 1.6.7.post1
   github:
     identifier: microsoft/debugpy
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="debugpy"
-        IMPORT_STATEMENT="import debugpy"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+  ignore-regex-patterns:
+    - 1.6.7.post1
+  manual: false
diff --git a/py3-defusedxml.yaml b/py3-defusedxml.yaml
--- a/py3-defusedxml.yaml
+++ b/py3-defusedxml.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-defusedxml
-  version: 0.7.1
-  epoch: 2
-  description: XML bomb protection for Python stdlib modules
-  copyright:
-    - license: PSF-2.0
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -20,42 +9,35 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: PSF-2.0
+  dependencies:
+    runtime:
+      - python3
+  description: XML bomb protection for Python stdlib modules
+  epoch: 2
+  name: py3-defusedxml
+  version: 0.7.1
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: ebff1b493751e2f0775314bdd4188d64f07ea184
       repository: https://github.com/tiran/defusedxml
       tag: v${{package.version}}
-      expected-commit: ebff1b493751e2f0775314bdd4188d64f07ea184
 
-  - runs: |
-      python3 -m gpep517 build-wheel \
-        --wheel-dir dist \
-        --output-fd 3 3>&1 >&2
-      python3 -m installer \
-        -d "${{targets.destdir}}" \
-        dist/defusedxml-${{package.version}}-*.whl
-      install -Dm644 LICENSE \
-        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE
+  - runs: "python3 -m gpep517 build-wheel \\\n  --wheel-dir dist \\\n  --output-fd 3 3>&1 >&2\npython3 -m installer \\\n  -d \"${{targets.destdir}}\" \\\n  dist/defusedxml-${{package.version}}-*.whl\ninstall -Dm644 LICENSE \\\n  \"${{targets.destdir}}\"/usr/share/licenses/${{package.name}}/LICENSE\n"
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"defusedxml\"\nIMPORT_STATEMENT=\"import defusedxml\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: tiran/defusedxml
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="defusedxml"
-        IMPORT_STATEMENT="import defusedxml"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-deprecation.yaml b/py3-deprecation.yaml
--- a/py3-deprecation.yaml
+++ b/py3-deprecation.yaml
@@ -1,16 +1,3 @@
-# Generated from https://pypi.org/project/deprecation/
-package:
-  name: py3-deprecation
-  version: 2.1.0
-  epoch: 3
-  description: A library to handle automated deprecations
-  copyright:
-    - license: Apache-2.0
-  dependencies:
-    runtime:
-      - py3-packaging
-      - python-3
-
 environment:
   contents:
     packages:
@@ -20,6 +7,18 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: Apache-2.0
+  dependencies:
+    runtime:
+      - py3-packaging
+      - python-3
+  description: A library to handle automated deprecations
+  epoch: 3
+  name: py3-deprecation
+  version: 2.1.0
 
 pipeline:
   - uses: git-checkout
@@ -33,23 +32,13 @@ pipeline:
 
   - uses: strip
 
-update:
-  enabled: true
-  manual: false
-  github:
-    identifier: briancurtin/deprecation
-
 test:
   pipeline:
-    - runs: |
-        LIBRARY="deprecation"
-        IMPORT_STATEMENT="import deprecation"
+    - runs: "LIBRARY=\"deprecation\"\nIMPORT_STATEMENT=\"import deprecation\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+update:
+  enabled: true
+  github:
+    identifier: briancurtin/deprecation
+  manual: false
diff --git a/py3-dill.yaml b/py3-dill.yaml
--- a/py3-dill.yaml
+++ b/py3-dill.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/dill/
-package:
-  name: py3-dill
-  version: 0.3.8
-  epoch: 0
-  description: serialize all of Python
-  copyright:
-    - license: BSD-3-Clause
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -19,6 +7,17 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: BSD-3-Clause
+  dependencies:
+    runtime:
+      - python-3
+  description: serialize all of Python
+  epoch: 0
+  name: py3-dill
+  version: 0.3.8
 
 pipeline:
   - uses: git-checkout
@@ -32,24 +31,14 @@ pipeline:
 
   - uses: strip
 
-update:
-  enabled: true
-  ignore-regex-patterns:
-    - dill-
-  github:
-    identifier: uqfoundation/dill
-
 test:
   pipeline:
-    - runs: |
-        LIBRARY="dill"
-        IMPORT_STATEMENT="import dill"
+    - runs: "LIBRARY=\"dill\"\nIMPORT_STATEMENT=\"import dill\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+update:
+  enabled: true
+  github:
+    identifier: uqfoundation/dill
+  ignore-regex-patterns:
+    - dill-
diff --git a/py3-distlib.yaml b/py3-distlib.yaml
--- a/py3-distlib.yaml
+++ b/py3-distlib.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/distlib/
-package:
-  name: py3-distlib
-  version: 0.3.8
-  epoch: 2
-  description: Distribution utilities
-  copyright:
-    - license: PSF-2.0
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,38 +9,42 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: PSF-2.0
+  dependencies:
+    runtime:
+      - python3
+  description: Distribution utilities
+  epoch: 2
+  name: py3-distlib
+  version: 0.3.8
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: ab5f8e797fbc56a0e3488bba68d05e7a602cb63f
       repository: https://github.com/pypa/distlib
       tag: ${{package.version}}
-      expected-commit: ab5f8e797fbc56a0e3488bba68d05e7a602cb63f
 
   - name: Python Build
-    runs: |
-      python -m build
+    runs: 'python -m build
+
       python3 -m installer -d "${{targets.destdir}}" dist/*.whl
-      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +
+
+      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf ''{}'' +
+
+    '
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "LIBRARY=\"distlib\"\nIMPORT_STATEMENT=\"import distlib\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: pypa/distlib
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="distlib"
-        IMPORT_STATEMENT="import distlib"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-docopt.yaml b/py3-docopt.yaml
--- a/py3-docopt.yaml
+++ b/py3-docopt.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/docopt/
-package:
-  name: py3-docopt
-  version: 0.6.2
-  epoch: 1
-  description: Pythonic argument parser, that will make you smile
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -19,6 +7,17 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python-3
+  description: Pythonic argument parser, that will make you smile
+  epoch: 1
+  name: py3-docopt
+  version: 0.6.2
 
 pipeline:
   - uses: fetch
@@ -31,22 +30,12 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"docopt\"\nIMPORT_STATEMENT=\"from docopt import docopt\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   release-monitor:
     identifier: 8436
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="docopt"
-        IMPORT_STATEMENT="from docopt import docopt"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-docutils.yaml b/py3-docutils.yaml
--- a/py3-docutils.yaml
+++ b/py3-docutils.yaml
@@ -1,15 +1,3 @@
-package:
-  name: py3-docutils
-  version: 0.21.2
-  epoch: 0
-  description: Documentation Utilities for Python3
-  copyright:
-    - license: BSD-2-Clause AND GPL-3.0-or-later AND Python-2.0
-  dependencies:
-    runtime:
-      - py3-pip
-      - python3
-
 environment:
   contents:
     packages:
@@ -20,33 +8,35 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: BSD-2-Clause AND GPL-3.0-or-later AND Python-2.0
+  dependencies:
+    runtime:
+      - py3-pip
+      - python3
+  description: Documentation Utilities for Python3
+  epoch: 0
+  name: py3-docutils
+  version: 0.21.2
+
 pipeline:
   - uses: fetch
     with:
-      uri: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${{package.version}}.tar.gz
       expected-sha256: 3a6b18732edf182daa3cd12775bbb338cf5691468f91eeeb109deff6ebfa986f
+      uri: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${{package.version}}.tar.gz
 
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"docutils\"\nIMPORT_STATEMENT=\"from docutils import nodes\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   release-monitor:
     identifier: 3849
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="docutils"
-        IMPORT_STATEMENT="from docutils import nodes"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
diff --git a/py3-dulwich.yaml b/py3-dulwich.yaml
--- a/py3-dulwich.yaml
+++ b/py3-dulwich.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/dulwich/
-package:
-  name: py3-dulwich
-  version: 0.22.1
-  epoch: 1
-  description: Python Git Library
-  copyright:
-    - license: Apache-2.0 AND GPL-2.0-or-later
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -20,36 +8,37 @@ environment:
       - python-3
       - wolfi-base
 
+package:
+  copyright:
+    - license: Apache-2.0 AND GPL-2.0-or-later
+  dependencies:
+    runtime:
+      - python-3
+  description: Python Git Library
+  epoch: 1
+  name: py3-dulwich
+  version: 0.22.1
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: 0fa636dc03e43477199ad7aefd917b628e93b29d
       repository: https://github.com/jelmer/dulwich
       tag: dulwich-${{package.version}}
-      expected-commit: 0fa636dc03e43477199ad7aefd917b628e93b29d
 
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"dulwich\"\nIMPORT_STATEMENT=\"import dulwich\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
   github:
     identifier: jelmer/dulwich
-    tag-filter: dulwich-
     strip-prefix: dulwich-
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="dulwich"
-        IMPORT_STATEMENT="import dulwich"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+    tag-filter: dulwich-
diff --git a/py3-escapism.yaml b/py3-escapism.yaml
--- a/py3-escapism.yaml
+++ b/py3-escapism.yaml
@@ -1,14 +1,3 @@
-package:
-  name: py3-escapism
-  version: 1.0.1
-  epoch: 0
-  description: Simple, generic API for escaping strings.
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python-3
-
 environment:
   contents:
     packages:
@@ -18,6 +7,17 @@ environment:
       - py3-setuptools
       - python-3
       - wolfi-base
+
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python-3
+  description: Simple, generic API for escaping strings.
+  epoch: 0
+  name: py3-escapism
+  version: 1.0.1
 
 pipeline:
   - uses: git-checkout
@@ -31,24 +31,14 @@ pipeline:
 
   - uses: strip
 
+test:
+  pipeline:
+    - runs: "LIBRARY=\"escapism\"\nIMPORT_STATEMENT=\"import escapism\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
+
 update:
   enabled: true
-  manual: false
   github:
     identifier: minrk/escapism
     use-tag: true
-
-test:
-  pipeline:
-    - runs: |
-        LIBRARY="escapism"
-        IMPORT_STATEMENT="import escapism"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+  manual: false
diff --git a/py3-git-filter-repo.yaml b/py3-git-filter-repo.yaml
--- a/py3-git-filter-repo.yaml
+++ b/py3-git-filter-repo.yaml
@@ -1,16 +1,3 @@
-# Generated from https://pypi.org/project/git-filter-repo/
-package:
-  name: py3-git-filter-repo
-  version: 2.45.0
-  epoch: 0
-  description: Quickly rewrite git repository history
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python-3
-      - git
-
 environment:
   contents:
     packages:
@@ -19,6 +6,18 @@ environment:
       - ca-certificates-bundle
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - git
+      - python-3
+  description: Quickly rewrite git repository history
+  epoch: 0
+  name: py3-git-filter-repo
+  version: 2.45.0
+
 pipeline:
   - uses: git-checkout
     with:
@@ -26,32 +25,18 @@ pipeline:
       repository: https://github.com/newren/git-filter-repo
       tag: v${{package.version}}
 
-  # pyproject.toml isn't included in the 2.83 branch
-  # It comes from https://github.com/newren/git-filter-repo/blob/main/pyproject.toml
   - name: Python Build
     uses: python/build-wheel
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: "cd $(mktemp -d)\ngit init\ngit config user.email \"you@example.com\"\ngit config user.name \"Your Name\"\ntouch README.md TEST.md\ngit add *\ngit commit -m \"Add files\"\ngit filter-repo --path README.md --force\ncount=$(ls |wc -l)\nif [ $count -ne 1 ]; then\n  echo \"failed to filter repo\"\n  exit 1\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
   github:
     identifier: newren/git-filter-repo
     strip-prefix: v
-
-test:
-  pipeline:
-    - runs: |
-        cd $(mktemp -d)
-        git init
-        git config user.email "you@example.com"
-        git config user.name "Your Name"
-        touch README.md TEST.md
-        git add *
-        git commit -m "Add files"
-        git filter-repo --path README.md --force
-        count=$(ls |wc -l)
-        if [ $count -ne 1 ]; then
-          echo "failed to filter repo"
-          exit 1
-        fi
diff --git a/py3-sqlglot.yaml b/py3-sqlglot.yaml
--- a/py3-sqlglot.yaml
+++ b/py3-sqlglot.yaml
@@ -1,15 +1,3 @@
-# Generated from https://pypi.org/project/sqlglot/
-package:
-  name: py3-sqlglot
-  version: 25.15.0
-  epoch: 0
-  description: An easily customizable SQL parser and transpiler
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - python3
-
 environment:
   contents:
     packages:
@@ -21,12 +9,23 @@ environment:
       - python3
       - wolfi-base
 
+package:
+  copyright:
+    - license: MIT
+  dependencies:
+    runtime:
+      - python3
+  description: An easily customizable SQL parser and transpiler
+  epoch: 0
+  name: py3-sqlglot
+  version: 25.15.0
+
 pipeline:
   - uses: git-checkout
     with:
+      expected-commit: be11f4c57c7842f69950bafc3225fb9c139af014
       repository: https://github.com/tobymao/sqlglot
       tag: v${{package.version}}
-      expected-commit: be11f4c57c7842f69950bafc3225fb9c139af014
 
   - name: Python Build
     runs: python setup.py build
@@ -38,18 +37,8 @@ pipeline:
 
 test:
   pipeline:
-    - runs: |
-        LIBRARY="sqlglot"
-        IMPORT_STATEMENT="import sqlglot"
-
-        if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'."
-            python -c "$IMPORT_STATEMENT" 2>&1
-            exit 1
-        else
-            echo "Library '$LIBRARY' is installed and can be imported successfully."
-            exit 0
-        fi
+    - runs: "LIBRARY=\"sqlglot\"\nIMPORT_STATEMENT=\"import sqlglot\"\n\nif ! python -c \"$IMPORT_STATEMENT\"; then\n    echo \"Failed to import library '$LIBRARY'.\"\n    python -c \"$IMPORT_STATEMENT\" 2>&1\n    exit 1\nelse\n    echo \"Library '$LIBRARY' is installed and can be imported successfully.\"\n    exit 0\nfi\n"
+    - uses: py/pip-check
 
 update:
   enabled: true
